### ISSUE TITLE
Adding dependency to gradle

### ISSUE THREAD

**Issue by adriantilvar** [cioccarellia/ksprefs#32]
Hey, i am getting an error when i try to add the     
implementation 'com.cioccarellia.ksprefs:2.0.0-rc1' to the gradle.

It says -> ERROR: Failed to resolve: com.cioccarellia.ksprefs:2.0.0-rc1:
Any idea why this is happening?

**Comment by cioccarellia** [comment]
I'm checking this out. Thanks for the report :)

**Comment by cioccarellia** [comment]
You should now be able to fetch ksprefs properly from maven.
Please stay tuned and make sure to wait until v2.0.0 before pushing your code into production :)

**Comment by cioccarellia** [comment]
Plus, we missed a semicolon between the group name and the package (`com.cioccarellia`and `ksprefs`).
My bad, it was like that in the readme. Now everything works fine
