### ISSUE TITLE
Exists is broken when encryption is enabled

### ISSUE THREAD

**Issue by csehtamas** [cioccarellia/ksprefs#38]
In `KspEnclosure` the `exists` method doesn't use `deriveKey` which breaks the method in case of encryption is enabled.

This
```
    internal fun exists(
        key: String
    ) = sharedReader.exists(key)
```

should be
```
    internal fun exists(
        key: String
    ) = sharedReader.exists(deriveKey(key))
```

Tested with 2.2.4 and 2.2.5

**Comment by cioccarellia** [comment]
Thanks! Nifty catch. Will be releasing an update today to address this, along with some documentation for internal classes and possibly some testing.
